require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/flights', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Flight. As you add validations to Flight, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      from: 'BGY', to: 'KRK', departure: Time.current + (60 * 60), arrival: Time.current + (60 * 60 * 3)
    }
  end

  let(:invalid_attributes) do
    {
      from: 'BGY', to: 'KRK', departure: Time.current - (60 * 60 * 2), arrival: Time.current - (60 * 60)
    }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # FlightsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Flight.create! valid_attributes
      get flights_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      flight = Flight.create! valid_attributes
      get flight_url(flight), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Flight' do
        expect do
          post flights_url,
               params: { flight: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Flight, :count).by(1)
      end

      it 'renders a JSON response with the new flight' do
        post flights_url,
             params: { flight: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Flight' do
        expect do
          post flights_url,
               params: { flight: invalid_attributes }, as: :json
        end.to change(Flight, :count).by(0)
      end

      it 'renders a JSON response with errors for the new flight' do
        post flights_url,
             params: { flight: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {from: "KRK", to: "BGY"}
      end

      it 'updates the requested flight' do
        flight = Flight.create! valid_attributes
        patch flight_url(flight),
              params: { flight: new_attributes }, headers: valid_headers, as: :json
        flight.reload
        expect(flight.from).to eq("KRK")
      end

      it 'renders a JSON response with the flight' do
        flight = Flight.create! valid_attributes
        patch flight_url(flight),
              params: { flight: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the flight' do
        flight = Flight.create! valid_attributes
        patch flight_url(flight),
              params: { flight: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested flight' do
      flight = Flight.create! valid_attributes
      expect do
        delete flight_url(flight), headers: valid_headers, as: :json
      end.to change(Flight, :count).by(-1)
    end
  end
end
